
CREATE DATABASE  IF NOT EXISTS blog;

USE blog;

CREATE TABLE BLOG (
    BLOG_ID            BIGINT(20) NOT NULL AUTO_INCREMENT,
    BLOG_CONTENT_LABLE VARCHAR(255) NOT NULL,
    BLOG_CONTENT       VARCHAR(255) NOT NULL,
    CREATED_DATE       DATE NOT NULL,
    MODIFIED_DATE      DATE,
    CONSTRAINT  PK_BLOG PRIMARY KEY (BLOG_ID)
);

CREATE TABLE ROLE (
 ROLE_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(255) NOT NULL,  
 CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_ID)
);

CREATE TABLE PERSON (
 PERSON_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
 ROLE_ID BIGINT(20) NOT NULL,
 USERNAME VARCHAR(255),
 PASSWORD VARCHAR(255),
 CONSTRAINT PK_PERSON PRIMARY KEY (PERSON_ID)
);



ALTER TABLE PERSON ADD(CONSTRAINT FK_PERSON_ROLE_ID
FOREIGN KEY (ROLE_ID)
REFERENCES ROLE(ROLE_ID));

INSERT INTO ROLE( NAME) VALUES( 'ROLE_ADMIN');
INSERT INTO ROLE( NAME) VALUES( 'ROLE_USER');

 /* password=admin  */
INSERT INTO PERSON( ROLE_ID,USERNAME,PASSWORD) VALUES( '1','admin', '0DPiKuNIrrVmD8IUCuw1hQxNqZc=');

/* password=user  */
INSERT INTO PERSON( ROLE_ID,USERNAME,PASSWORD) VALUES( '2','user', 'Et6pb+wgWTVmq3VpLJlJWWgzrck=');


